FROM python:3.10.12

# Copy project files
COPY . .

# Install dependencies
RUN pip install -r requirements.txt

# Copy the entrypoint script and make it executable
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Expose the port
EXPOSE 8000

# Use the entrypoint script as the command
CMD ["./entrypoint.sh"]
