# Generated by Django 5.1.3 on 2024-11-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='work_from',
            field=models.CharField(choices=[('WFH', 'Work From Home'), ('WFO', 'Work From Office'), ('H', 'Hybrid')], default='WFH', max_length=30),
            preserve_default=False,
        ),
    ]
